server:
  applicationConnectors:
  - type: http
    port: 9000
  adminConnectors:
  - type: http
    port: 9001
  requestLog:
    appenders: []
logging:
  level: OFF
  loggers:
    "com.github.victorcombalweiss": INFO
